### ISSUE TITLE
where is the xml files?

### ISSUE THREAD

**Issue by chenchuang911** [docusign/recipe-010-webhook-java#1]
![2017-01-19 17-44-11](https://cloud.githubusercontent.com/assets/23691950/22101586/06f1eeec-de6f-11e6-965d-e9580b8332c5.png)

When i deploy the java app on heroku, i can't find the xml files. But there are xml files when i deploy the php app on heroku. Why? Is this a bug?

**Comment by mmallis87** [comment]
@chuang911 this looks like a bug with the Java version only. Please use any other language, till it's fixed.

**Comment by chenchuang911** [comment]
Now i can receive xml use java, but i will receive the DocumentPDFs in the xml file when i set setIncludeDocuments **false** whit the EventNotification. And i won't receive the DocumentPDFs before The Chinese New Year.

![image](https://cloud.githubusercontent.com/assets/23691950/22675554/6c31ac96-ed21-11e6-94fe-a6460778046d.png)
